### ISSUE TITLE
Link from session page?

### ISSUE THREAD

**Issue by timholy** [aviatesk/juliacon2021-workshop-pkgdev#9]
Are we ready to advertise this? We will want to add this repo as a "resource" to our session page.

**Comment by aviatesk** [comment]
Actually I already modified our pretalx description and even asked the organizers to reflect the change to the description of our YouTube video :)

But we may want to advertise this somewhere else as well ?

**Comment by timholy** [comment]
I don't see the link here: https://pretalx.com/juliacon2021/talk/VY9UVX/

**Comment by timholy** [comment]
I went ahead and linked it.
